# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python

# Available Python versions:
# http://about.travis-ci.org/docs/user/ci-environment/#Python-VM-images
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
 - pip install PyYAML
 - pip install pylint==1.3.1
 - pip install pyflakes
 - pip install pep8
script:
  - pep8 setup.py pytravis
  - pylint setup.py pytravis
  - pyflakes setup.py pytravis
  - nosetests pytravis
